build:
    nodes:
        analysis:
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress
filter:
    excluded_paths:
        - 'assets/u2f-api.min.js'
        - 'assets/u2f-api.js'
    dependency_paths:
        - wordpress/

checks:
    php:
        code_rating: true
        duplication: true
